cart:
  fullnameOverride: carts

  serviceAccount:
    create: false
    name: carts

  app:
    persistence:
      provider: dynamodb
      dynamodb:
        tableName: project-bedrock-carts
        createTable: false

  dynamodb:
    create: false

catalog:
  fullnameOverride: catalog

  app:
    persistence:
      provider: mysql
      endpoint: project-bedrock-catalog-mysql.c2hcqsu0kmwi.us-east-1.rds.amazonaws.com:3306
      database: catalog

      secret:
        create: false
        name: catalog-db
        username: catalog
        password: ""

  mysql:
    create: false

checkout:
  fullnameOverride: checkout

  app:
    persistence:
      provider: redis
      redis:
        endpoint: ""
        tls: false

    endpoints:
      orders: http://orders:80

  redis:
    create: true

orders:
  fullnameOverride: orders

  app:
    persistence:
      provider: postgres
      endpoint: project-bedrock-orders-postgres.c2hcqsu0kmwi.us-east-1.rds.amazonaws.com:5432
      database: orders

      secret:
        create: false
        name: orders-db
        username: orders
        password: ""

    messaging:
      provider: rabbitmq

      rabbitmq:
        addresses: []

        secret:
          create: true
          name: orders-rabbitmq
          username: guest
          password: guest

  postgresql:
    create: false

  rabbitmq:
    create: true
    persistentVolume:
      enabled: false

ui:
  fullnameOverride: ui

  app:
    endpoints:
      catalog: http://catalog:80
      carts: http://carts:80
      checkout: http://checkout:80
      orders: http://orders:80

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    className: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:940567657040:certificate/ac4fbc1a-423e-441c-a209-7311102514fd
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/healthcheck-path: /actuator/health/liveness
    hosts:
      - store.chnd.space